name = "individual"
uuid = "fc91e7d7-639c-4584-a1b8-453dd568b9a2"
authors = ["Sean L. Wu <slwood89@gmail.com>"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
